### ISSUE TITLE
ePas ha generato un errore inaspettato. Riprovare o effettuare una segnalazione.

### ISSUE THREAD

**Issue by lucanatalegov** [consiglionazionaledellericerche/epas#198]
Dopo aver intallato epas la versione15 e aver confifurato degli istituti e delle sedi al successivo accesso epas mi restituisec il seguente errore:

ePas ha generato un errore inaspettato. Riprovare o effettuare una segnalazione.

Nel file di log compare il seguente errore:

Internal Server Error (500) for request GET /epas/

Execution exception (In /app/controllers/RequestInit.java around line 197)
NoSuchElementException occurred : No value present

play.exceptions.JavaExecutionException: No value present
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:495)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:477)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:444)
        at play.mvc.ActionInvoker.handleBefores(ActionInvoker.java:307)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:148)
        at Invocation.HTTP Request(Play!)
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Unknown Source)
        at controllers.RequestInit.injectMenu(RequestInit.java:197)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:485)
        ... 5 more

Come poos risolvere il problema?

**Comment by criluc** [comment]
Il problema sembra legato alla lista degli uffici su cui l'utente corrente ha almeno un ruolo presente.

Quali sono i ruoli di sistema dell'utente con cui da questo errore? E i suoi ruoli negli uffici presenti nel sistema?
Gli uffici su cui possiede dei ruoli hanno la data di chiusura impostata?

L'errore potrebbe essere legato al fatto che l'utente corrente abbia dei dei ruoli su una lista tutti e solo con data di chiusura impostata cioè non ci sono ufficio con endDate==null, vedi offices.stream().filter(off -> off.getEndDate() == null)  in https://github.com/consiglionazionaledellericerche/epas/blob/main/app/controllers/RequestInit.java#L197

**Comment by lucanatalegov** [comment]
Il problema si verifica se non c'e nessun utente configurato.
Lo scenario in cui si verifica il problema è:

  1.
Installazione di epas
  2.
accesso ad epas con utente admin
  3.
cambio password dell'utente admin
  4.
configurazione nuovo istituto e nuovo ufficio ( senza configurare nessun utente)
  5.
stop di epas
  6.
avvio di epas
  7.
Connessione ad epas con utetnte admin
  8.
epas va in errore.

Ciao
Luca
________________________________
Da: Cristian Lucchesi ***@***.***>
Inviato: giovedì 27 giugno 2024 16:51
A: consiglionazionaledellericerche/epas ***@***.***>
Cc: Natale Luca ***@***.***>; Author ***@***.***>
Oggetto: Re: [consiglionazionaledellericerche/epas] ePas ha generato un errore inaspettato. Riprovare o effettuare una segnalazione. (Issue #198)


Il problema sembra legato alla lista degli uffici su cui l'utente corrente ha almeno un ruolo presente.

Quali sono i ruoli di sistema dell'utente con cui da questo errore? E i suoi ruoli negli uffici presenti nel sistema?
Gli uffici su cui possiede dei ruoli hanno la data di chiusura impostata?

L'errore potrebbe essere legato al fatto che l'utente corrente abbia dei dei ruoli su una lista tutti e solo con data di chiusura impostata cioè non ci sono ufficio con endDate==null, vedi offices.stream().filter(off -> off.getEndDate() == null) in https://github.com/consiglionazionaledellericerche/epas/blob/main/app/controllers/RequestInit.java#L197

**Comment by criluc** [comment]
@lucanatalegov abbiamo individuato il problema che si verifica seguendo i passi che hai indicato, sarà risolto nella versione 2.18.0. 
Per adesso dovresti evitare di cambiare il nome dell'ufficio iniziale prima di aver inserito almeno una persona al suo interno.
