### ISSUE TITLE
L'inserimento di una richiesta di cambio reperibilità senza avere un giorno in cambio da errore

### ISSUE THREAD

**Issue by criluc** [consiglionazionaledellericerche/epas#245]
Caused by: java.lang.IllegalArgumentException: Either from or to needs to be non-null
        at com.querydsl.core.types.dsl.ComparableExpression.between(ComparableExpression.java:59)
        at dao.CompetenceRequestDao.existingCompetenceRequests(CompetenceRequestDao.java:351)
        at manager.flows.CompetenceRequestManager.checkCompetenceRequest(CompetenceRequestManager.java:550)

**Comment by criluc** [comment]
Duplicato del #412
